version: 2
jobs:
  build:
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/ruby:2.4.1
    steps: 
      - checkout
      - setup_remote_docker
      - run: echo "A first hello"
