version: 2
jobs:
  build:
    machine: true
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps: 
      - checkout
      - run: echo "A first hello"
