version: 2
jobs:
  build:
    machine: true
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps: 
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: git config --global user.email "info@slatwallcommerce.com"
      - run: git config --global user.name "Big Boy (Slatwall Robot)"
      - run: git config --global push.default current
      - run: npm install -g webpack@1.13.3 gulp less
      - run: npm install gulp gulp-inject@3 gulp-chmod@1.3.0 gulp-util run-sequence webpack@1.13.3 force-case-sensitivity-webpack-plugin strip-loader ng-annotate-webpack-plugin tsify typescript ts-loader@1.3.0 md5 blueimp-md5
      
